image_size: 32 # Reduced from 256 to fix OOM
num_layers: 1
weight_initializer: InitWeights_He  # From unet_util
linear_attn_layers: null  # Or list like [true, true, true, false]
skip_connect_image_feature_maps: false
first_conv_channels: 8
time_embedding_dim: 128
mask_channels: 1
output_channels: 1
image_channels: 2
att_heads: 2
att_head_dim: 2
bottleneck_transformer_layers: 1
architecture: "medsegdiff"