# Base cluster environment config (no diffusion or logging pairing)

defaults:
  - _self_
  - environment: isles_cluster
  - model: medsegdiff_256_4l_16c_6x4a_128t_1btl_large
  - dataset: isles24
  - training: train_100Kms_50Ks_9999e
  - optimizer: opt_2e4lr_reducelrs_075f_2p_1e4t_1c_1Ki
  - logging: default  # baseline; wrappers may override
  - diffusion: openai_ddpm_100ts_debug
  - validation: default

random_seed: 42
mode: train  # or evaluate

timestamp: null
run_name: null

hydra:
  run:
    dir: '.'
