# Base local environment config
defaults:
  - _self_
  - environment: isles_local
  - distribution: dp
  - model: medsegdiff_32_1l_8c_2x2a_128t_1btl_debug
  - dataset: isles24
  - augmentation: none
  - training: train_100Kms_50Ks_9999e
  - optimizer: adamw_2e4lr_wd00
  - scheduler: warmup_cosine_10pct
  - logging: default
  - loss: mse_loss_only
  - diffusion: openai_ddpm_100ts_debug
  - validation: default

random_seed: 42
mode: train

hydra:
  run:
    dir: '.'
