# Base local environment config
defaults:
  - _self_
  - environment: isles_local
  - model: medsegdiff_32_1l_8c_2x2a_128t_1btl_debug
  - dataset: isles24
  - training: train_100Kms_50Ks_9999e
  - optimizer: opt_2e4lr_reducelrs_075f_4p_1e4t_3c_1Ki
  - logging: default
  - loss: mse_only
  - diffusion: openai_ddpm_100ts_debug
  - validation: default

random_seed: 42
mode: train

hydra:
  run:
    dir: '.'
